require_relative '../node_modules/react-native-macos/scripts/react_native_pods'

prepare_react_native_project!

target 'dunefresh-macOS' do
  platform :macos, '11.0'
  use_native_modules!

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'FileCore', :path => './FileCore'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
