require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

target 'dune-macOS' do
  platform :macos, '11.0'
  use_native_modules!

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :hermes_enabled => true,
    :fabric_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)
    # Ensure Pods use the same deployment target and C++ standard
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |c|
        c.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.0'
        c.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        c.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      end
    end
  end
end
